### PR TITLE
Fix 'Show Desktop' hiding skins on Windows 11 24H2

### LINKED ISSUE #377: On Windows 11 24H2: showing desktop will hide rainmeter widgets
On Windows 11 24H2 (Build 26xxx), showing desktop by pressing Win+D or clicking the right corner of taskbar will cause all rainmeter widgets to disappear as well.

It affects all current 24h2 builds (Canary, Dev or Release Preview). 23H2 is not affected.

### PR DESCRIPTION
**Pull request by poiru**
Win+D and the 'Show Desktop' button were both hiding skins on Windows 11 24H2. We now account for the changes in the desktop WorkerW hierarchy and limit the change to recent builds of Windows 11 to limit affecting older operating systems.

Fixes #377

### CODE REVIEW

File: Library/System.cpp [hunk 1]
```diff
@@ -662,6 +662,32 @@ HWND System::GetDefaultShellWindow()
 	return ShellW;
 }
 
+// Windows 11 24H2 reordered the the desktop windows.
```
Comment (raziel-) [inline Library/System.cpp:665]: "the the"
